spring:
  datasource:
    url: jdbc:h2:mem:pre-voyage
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
