spring:
  profiles:
    active: api
  datasource:
    url: jdbc:sqlite:pre-voyage.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret-key: cHJlX3ZveWFnZS1oYW5naGFlX3BsdXMtZnJhbWV3b3JrX3N0dWR5LWp3dA==
